server.id=wumpus-server
server.port=8080
server.path=/socket
kafka.bootstrap.servers=localhost:9091
kafka.key.serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.value.serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.group.id=wumpus-group
topics.account=account
topics.command=command
topics.outbound=outbound